/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BodyRouteImport } from './routes/body'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LockerRouteImport } from './routes/locker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as LibraryIdRouteImport } from './routes/library.$id'
import { Route as MomentsIdRouteImport } from './routes/moments.$id'
import { Route as ProgramsIdRouteImport } from './routes/programs.$id'
import { Route as RoutinesIdRouteImport } from './routes/routines.$id'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ToolsPlatesRouteImport } from './routes/tools.plates'
import { Route as ToolsWarmupRouteImport } from './routes/tools.warmup'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkoutIdSummaryRouteImport } from './routes/workout.$id.summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerRoute = LockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LibraryRoute,
} as any)
const MomentsIdRoute = MomentsIdRouteImport.update({
  id: '/moments/$id',
  path: '/moments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdRoute = ProgramsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsRoute,
} as any)
const RoutinesIdRoute = RoutinesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoutinesRoute,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPlatesRoute = ToolsPlatesRouteImport.update({
  id: '/plates',
  path: '/plates',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsWarmupRoute = ToolsWarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => ToolsRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdSummaryRoute = WorkoutIdSummaryRouteImport.update({
  id: '/$id/summary',
  path: '/$id/summary',
  getParentRoute: () => WorkoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/body': typeof BodyRoute
  '/chronicle': typeof ChronicleRoute
  '/history': typeof HistoryRouteWithChildren
  '/lab': typeof LabRoute
  '/library': typeof LibraryRouteWithChildren
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/vault': typeof VaultRoute
  '/workout': typeof WorkoutRouteWithChildren
  '/wrapped': typeof WrappedRoute
  '/history/$id': typeof HistoryIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/moments/$id': typeof MomentsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/s/$id': typeof SIdRoute
  '/tools/plates': typeof ToolsPlatesRoute
  '/tools/warmup': typeof ToolsWarmupRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workout/$id/summary': typeof WorkoutIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/body': typeof BodyRoute
  '/chronicle': typeof ChronicleRoute
  '/history': typeof HistoryRouteWithChildren
  '/lab': typeof LabRoute
  '/library': typeof LibraryRouteWithChildren
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/vault': typeof VaultRoute
  '/workout': typeof WorkoutRouteWithChildren
  '/wrapped': typeof WrappedRoute
  '/history/$id': typeof HistoryIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/moments/$id': typeof MomentsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/s/$id': typeof SIdRoute
  '/tools/plates': typeof ToolsPlatesRoute
  '/tools/warmup': typeof ToolsWarmupRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workout/$id/summary': typeof WorkoutIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/body': typeof BodyRoute
  '/chronicle': typeof ChronicleRoute
  '/history': typeof HistoryRouteWithChildren
  '/lab': typeof LabRoute
  '/library': typeof LibraryRouteWithChildren
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/vault': typeof VaultRoute
  '/workout': typeof WorkoutRouteWithChildren
  '/wrapped': typeof WrappedRoute
  '/history/$id': typeof HistoryIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/moments/$id': typeof MomentsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/s/$id': typeof SIdRoute
  '/tools/plates': typeof ToolsPlatesRoute
  '/tools/warmup': typeof ToolsWarmupRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workout/$id/summary': typeof WorkoutIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/body'
    | '/chronicle'
    | '/history'
    | '/lab'
    | '/library'
    | '/locker'
    | '/login'
    | '/more'
    | '/programs'
    | '/routines'
    | '/settings'
    | '/tools'
    | '/vault'
    | '/workout'
    | '/wrapped'
    | '/history/$id'
    | '/library/$id'
    | '/moments/$id'
    | '/programs/$id'
    | '/routines/$id'
    | '/s/$id'
    | '/tools/plates'
    | '/tools/warmup'
    | '/u/$handle'
    | '/api/auth/$'
    | '/workout/$id/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/body'
    | '/chronicle'
    | '/history'
    | '/lab'
    | '/library'
    | '/locker'
    | '/login'
    | '/more'
    | '/programs'
    | '/routines'
    | '/settings'
    | '/tools'
    | '/vault'
    | '/workout'
    | '/wrapped'
    | '/history/$id'
    | '/library/$id'
    | '/moments/$id'
    | '/programs/$id'
    | '/routines/$id'
    | '/s/$id'
    | '/tools/plates'
    | '/tools/warmup'
    | '/u/$handle'
    | '/api/auth/$'
    | '/workout/$id/summary'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/body'
    | '/chronicle'
    | '/history'
    | '/lab'
    | '/library'
    | '/locker'
    | '/login'
    | '/more'
    | '/programs'
    | '/routines'
    | '/settings'
    | '/tools'
    | '/vault'
    | '/workout'
    | '/wrapped'
    | '/history/$id'
    | '/library/$id'
    | '/moments/$id'
    | '/programs/$id'
    | '/routines/$id'
    | '/s/$id'
    | '/tools/plates'
    | '/tools/warmup'
    | '/u/$handle'
    | '/api/auth/$'
    | '/workout/$id/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BodyRoute: typeof BodyRoute
  ChronicleRoute: typeof ChronicleRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LabRoute: typeof LabRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  LockerRoute: typeof LockerRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  RoutinesRoute: typeof RoutinesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  VaultRoute: typeof VaultRoute
  WorkoutRoute: typeof WorkoutRouteWithChildren
  WrappedRoute: typeof WrappedRoute
  MomentsIdRoute: typeof MomentsIdRoute
  SIdRoute: typeof SIdRoute
  UHandleRoute: typeof UHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker': {
      id: '/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof LockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/moments/$id': {
      id: '/moments/$id'
      path: '/moments/$id'
      fullPath: '/moments/$id'
      preLoaderRoute: typeof MomentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id': {
      id: '/programs/$id'
      path: '/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/routines/$id': {
      id: '/routines/$id'
      path: '/$id'
      fullPath: '/routines/$id'
      preLoaderRoute: typeof RoutinesIdRouteImport
      parentRoute: typeof RoutinesRoute
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/plates': {
      id: '/tools/plates'
      path: '/plates'
      fullPath: '/tools/plates'
      preLoaderRoute: typeof ToolsPlatesRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/warmup': {
      id: '/tools/warmup'
      path: '/warmup'
      fullPath: '/tools/warmup'
      preLoaderRoute: typeof ToolsWarmupRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$id/summary': {
      id: '/workout/$id/summary'
      path: '/$id/summary'
      fullPath: '/workout/$id/summary'
      preLoaderRoute: typeof WorkoutIdSummaryRouteImport
      parentRoute: typeof WorkoutRoute
    }
  }
}

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface LibraryRouteChildren {
  LibraryIdRoute: typeof LibraryIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryIdRoute: LibraryIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface ProgramsRouteChildren {
  ProgramsIdRoute: typeof ProgramsIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsIdRoute: ProgramsIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface RoutinesRouteChildren {
  RoutinesIdRoute: typeof RoutinesIdRoute
}

const RoutinesRouteChildren: RoutinesRouteChildren = {
  RoutinesIdRoute: RoutinesIdRoute,
}

const RoutinesRouteWithChildren = RoutinesRoute._addFileChildren(
  RoutinesRouteChildren,
)

interface ToolsRouteChildren {
  ToolsPlatesRoute: typeof ToolsPlatesRoute
  ToolsWarmupRoute: typeof ToolsWarmupRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsPlatesRoute: ToolsPlatesRoute,
  ToolsWarmupRoute: ToolsWarmupRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface WorkoutRouteChildren {
  WorkoutIdSummaryRoute: typeof WorkoutIdSummaryRoute
}

const WorkoutRouteChildren: WorkoutRouteChildren = {
  WorkoutIdSummaryRoute: WorkoutIdSummaryRoute,
}

const WorkoutRouteWithChildren =
  WorkoutRoute._addFileChildren(WorkoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BodyRoute: BodyRoute,
  ChronicleRoute: ChronicleRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LabRoute: LabRoute,
  LibraryRoute: LibraryRouteWithChildren,
  LockerRoute: LockerRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  RoutinesRoute: RoutinesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  VaultRoute: VaultRoute,
  WorkoutRoute: WorkoutRouteWithChildren,
  WrappedRoute: WrappedRoute,
  MomentsIdRoute: MomentsIdRoute,
  SIdRoute: SIdRoute,
  UHandleRoute: UHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
