/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BodyRouteImport } from './routes/body'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LockerRouteImport } from './routes/locker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as HTokenRouteImport } from './routes/h.$token'
import { Route as HistoryIdRouteImport } from './routes/history_.$id'
import { Route as LibraryIdRouteImport } from './routes/library_.$id'
import { Route as MomentsIdRouteImport } from './routes/moments.$id'
import { Route as ProgramsIdRouteImport } from './routes/programs_.$id'
import { Route as RoutinesIdRouteImport } from './routes/routines_.$id'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ToolsPlatesRouteImport } from './routes/tools_.plates'
import { Route as ToolsWarmupRouteImport } from './routes/tools_.warmup'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkoutIdSummaryRouteImport } from './routes/workout_.$id.summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerRoute = LockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const HTokenRoute = HTokenRouteImport.update({
  id: '/h/$token',
  path: '/h/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history_/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/library_/$id',
  path: '/library/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsIdRoute = MomentsIdRouteImport.update({
  id: '/moments/$id',
  path: '/moments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdRoute = ProgramsIdRouteImport.update({
  id: '/programs_/$id',
  path: '/programs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIdRoute = RoutinesIdRouteImport.update({
  id: '/routines_/$id',
  path: '/routines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPlatesRoute = ToolsPlatesRouteImport.update({
  id: '/tools_/plates',
  path: '/tools/plates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWarmupRoute = ToolsWarmupRouteImport.update({
  id: '/tools_/warmup',
  path: '/tools/warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdSummaryRoute = WorkoutIdSummaryRouteImport.update({
  id: '/workout_/$id/summary',
  path: '/workout/$id/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/body': typeof BodyRoute
  '/chronicle': typeof ChronicleRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/lab': typeof LabRoute
  '/library': typeof LibraryRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/programs': typeof ProgramsRoute
  '/receipt': typeof ReceiptRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/vault': typeof VaultRoute
  '/workout': typeof WorkoutRoute
  '/wrapped': typeof WrappedRoute
  '/h/$token': typeof HTokenRoute
  '/history/$id': typeof HistoryIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/moments/$id': typeof MomentsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/s/$id': typeof SIdRoute
  '/tools/plates': typeof ToolsPlatesRoute
  '/tools/warmup': typeof ToolsWarmupRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workout/$id/summary': typeof WorkoutIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/body': typeof BodyRoute
  '/chronicle': typeof ChronicleRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/lab': typeof LabRoute
  '/library': typeof LibraryRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/programs': typeof ProgramsRoute
  '/receipt': typeof ReceiptRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/vault': typeof VaultRoute
  '/workout': typeof WorkoutRoute
  '/wrapped': typeof WrappedRoute
  '/h/$token': typeof HTokenRoute
  '/history/$id': typeof HistoryIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/moments/$id': typeof MomentsIdRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/s/$id': typeof SIdRoute
  '/tools/plates': typeof ToolsPlatesRoute
  '/tools/warmup': typeof ToolsWarmupRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workout/$id/summary': typeof WorkoutIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/body': typeof BodyRoute
  '/chronicle': typeof ChronicleRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/lab': typeof LabRoute
  '/library': typeof LibraryRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/programs': typeof ProgramsRoute
  '/receipt': typeof ReceiptRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/vault': typeof VaultRoute
  '/workout': typeof WorkoutRoute
  '/wrapped': typeof WrappedRoute
  '/h/$token': typeof HTokenRoute
  '/history_/$id': typeof HistoryIdRoute
  '/library_/$id': typeof LibraryIdRoute
  '/moments/$id': typeof MomentsIdRoute
  '/programs_/$id': typeof ProgramsIdRoute
  '/routines_/$id': typeof RoutinesIdRoute
  '/s/$id': typeof SIdRoute
  '/tools_/plates': typeof ToolsPlatesRoute
  '/tools_/warmup': typeof ToolsWarmupRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workout_/$id/summary': typeof WorkoutIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/body'
    | '/chronicle'
    | '/history'
    | '/import'
    | '/lab'
    | '/library'
    | '/locker'
    | '/login'
    | '/more'
    | '/programs'
    | '/receipt'
    | '/routines'
    | '/settings'
    | '/tools'
    | '/vault'
    | '/workout'
    | '/wrapped'
    | '/h/$token'
    | '/history/$id'
    | '/library/$id'
    | '/moments/$id'
    | '/programs/$id'
    | '/routines/$id'
    | '/s/$id'
    | '/tools/plates'
    | '/tools/warmup'
    | '/u/$handle'
    | '/api/auth/$'
    | '/workout/$id/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/body'
    | '/chronicle'
    | '/history'
    | '/import'
    | '/lab'
    | '/library'
    | '/locker'
    | '/login'
    | '/more'
    | '/programs'
    | '/receipt'
    | '/routines'
    | '/settings'
    | '/tools'
    | '/vault'
    | '/workout'
    | '/wrapped'
    | '/h/$token'
    | '/history/$id'
    | '/library/$id'
    | '/moments/$id'
    | '/programs/$id'
    | '/routines/$id'
    | '/s/$id'
    | '/tools/plates'
    | '/tools/warmup'
    | '/u/$handle'
    | '/api/auth/$'
    | '/workout/$id/summary'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/body'
    | '/chronicle'
    | '/history'
    | '/import'
    | '/lab'
    | '/library'
    | '/locker'
    | '/login'
    | '/more'
    | '/programs'
    | '/receipt'
    | '/routines'
    | '/settings'
    | '/tools'
    | '/vault'
    | '/workout'
    | '/wrapped'
    | '/h/$token'
    | '/history_/$id'
    | '/library_/$id'
    | '/moments/$id'
    | '/programs_/$id'
    | '/routines_/$id'
    | '/s/$id'
    | '/tools_/plates'
    | '/tools_/warmup'
    | '/u/$handle'
    | '/api/auth/$'
    | '/workout_/$id/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BodyRoute: typeof BodyRoute
  ChronicleRoute: typeof ChronicleRoute
  HistoryRoute: typeof HistoryRoute
  ImportRoute: typeof ImportRoute
  LabRoute: typeof LabRoute
  LibraryRoute: typeof LibraryRoute
  LockerRoute: typeof LockerRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  ProgramsRoute: typeof ProgramsRoute
  ReceiptRoute: typeof ReceiptRoute
  RoutinesRoute: typeof RoutinesRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  VaultRoute: typeof VaultRoute
  WorkoutRoute: typeof WorkoutRoute
  WrappedRoute: typeof WrappedRoute
  HTokenRoute: typeof HTokenRoute
  HistoryIdRoute: typeof HistoryIdRoute
  LibraryIdRoute: typeof LibraryIdRoute
  MomentsIdRoute: typeof MomentsIdRoute
  ProgramsIdRoute: typeof ProgramsIdRoute
  RoutinesIdRoute: typeof RoutinesIdRoute
  SIdRoute: typeof SIdRoute
  ToolsPlatesRoute: typeof ToolsPlatesRoute
  ToolsWarmupRoute: typeof ToolsWarmupRoute
  UHandleRoute: typeof UHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  WorkoutIdSummaryRoute: typeof WorkoutIdSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker': {
      id: '/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof LockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$token': {
      id: '/h/$token'
      path: '/h/$token'
      fullPath: '/h/$token'
      preLoaderRoute: typeof HTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$id': {
      id: '/history_/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$id': {
      id: '/library_/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments/$id': {
      id: '/moments/$id'
      path: '/moments/$id'
      fullPath: '/moments/$id'
      preLoaderRoute: typeof MomentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/$id': {
      id: '/programs_/$id'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines_/$id': {
      id: '/routines_/$id'
      path: '/routines/$id'
      fullPath: '/routines/$id'
      preLoaderRoute: typeof RoutinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools_/plates': {
      id: '/tools_/plates'
      path: '/tools/plates'
      fullPath: '/tools/plates'
      preLoaderRoute: typeof ToolsPlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools_/warmup': {
      id: '/tools_/warmup'
      path: '/tools/warmup'
      fullPath: '/tools/warmup'
      preLoaderRoute: typeof ToolsWarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout_/$id/summary': {
      id: '/workout_/$id/summary'
      path: '/workout/$id/summary'
      fullPath: '/workout/$id/summary'
      preLoaderRoute: typeof WorkoutIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BodyRoute: BodyRoute,
  ChronicleRoute: ChronicleRoute,
  HistoryRoute: HistoryRoute,
  ImportRoute: ImportRoute,
  LabRoute: LabRoute,
  LibraryRoute: LibraryRoute,
  LockerRoute: LockerRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  ProgramsRoute: ProgramsRoute,
  ReceiptRoute: ReceiptRoute,
  RoutinesRoute: RoutinesRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  VaultRoute: VaultRoute,
  WorkoutRoute: WorkoutRoute,
  WrappedRoute: WrappedRoute,
  HTokenRoute: HTokenRoute,
  HistoryIdRoute: HistoryIdRoute,
  LibraryIdRoute: LibraryIdRoute,
  MomentsIdRoute: MomentsIdRoute,
  ProgramsIdRoute: ProgramsIdRoute,
  RoutinesIdRoute: RoutinesIdRoute,
  SIdRoute: SIdRoute,
  ToolsPlatesRoute: ToolsPlatesRoute,
  ToolsWarmupRoute: ToolsWarmupRoute,
  UHandleRoute: UHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  WorkoutIdSummaryRoute: WorkoutIdSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
